# Generated by Django 3.0.6 on 2020-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200525_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='timestamp',
            field=models.CharField(max_length=50),
        ),
    ]
